version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - REDIS_REPLICA_IP=${LOCAL_IP}
      - REDIS_REPLICA_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis-net
    ports:
      - '6379:6379'
      
  redis-slave:
    image: 'bitnami/redis:latest'
    container_name: redis-slave
    environment:
      - REDIS_REPLICA_IP=${LOCAL_IP}
      - REDIS_REPLICA_PORT=6380
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=${LOCAL_IP}
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    depends_on:
      - redis
    networks:
      - redis-net
      
  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    container_name: redis-sentinel-1
    environment:
      - REDIS_MASTER_HOST=${LOCAL_IP}
      - REDIS_SENTINEL_ANNOUNCE_IP=${LOCAL_IP}
      - REDIS_SENTINEL_PORT_NUMBER=26379
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      - redis-net
      
  redis-sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    container_name: redis-sentinel-2
    environment:
      - REDIS_MASTER_HOST=${LOCAL_IP}
      - REDIS_SENTINEL_ANNOUNCE_IP=${LOCAL_IP}
      - REDIS_SENTINEL_PORT_NUMBER=26380
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26380:26380'
    networks:
      - redis-net
      
  redis-sentinel-3:
    image: 'bitnami/redis-sentinel:latest'
    container_name: redis-sentinel-3
    environment:
      - REDIS_MASTER_HOST=${LOCAL_IP}
      - REDIS_SENTINEL_ANNOUNCE_IP=${LOCAL_IP}
      - REDIS_SENTINEL_PORT_NUMBER=26381
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26381:26381'
    networks:
      - redis-net      
      
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
      - SENTINELS=redis-sentinel-1:26379,redis-sentinel-2:26380,redis-sentinel-3:26381
    ports:
      - "8888:8081"
    depends_on:
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
    networks:
      - redis-net
    
networks:
  redis-net:
    driver: bridge