FROM maven:3.6.0-jdk-11-slim AS build
COPY ./src /home/app/src
COPY pom.xml /home/app
COPY settings.xml /root/.m2/
RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:11-jre-slim
COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar
EXPOSE 9000
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Xss512k -Xms100m -Xmx100m -Duser.timezone=GMT+3 -Dspring.profiles.active=$APP_PROF -jar /usr/local/lib/app.jar" ]