spring:
  application:
    name: https-client

demo:
  url: https://localhost:443
  path:
    test: /test
  ssl:
    secure-enable: true
    pathToTrustStore: classpath:truststore/client_truststore.jks
    trustStorePassword: password

server:
  port: 8181